language: swift
os: osx
osx_image: xcode9.4

script:
  - xcodebuild \
    -workspace /Example/ImageAlertAction.xcworkspace \
    -scheme ImageAlertAction-Example \
    build-for-testing
  - xctool \
    -workspace /Example/ImageAlertAction.xcworkspace \
    -scheme ImageAlertAction-Example \
    run-tests

