language: swift
osx_image: xcode9.4
script:
  - xcodebuild clean test -workspace Example/ImageAlertAction.xcworkspace -scheme ImageAlertAction-Example -destination "platform=iOS Simulator,name=iPhone X,OS=11.3" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO -quiet
