language: swift
osx_image: xcode11.1

script:
  - cd Example/
  - pod install
  - cd ..
  - xcodebuild clean test -scheme ImageAlertAction-Example -workspace Example/ImageAlertAction.xcworkspace -destination "platform=iOS Simulator,name=iPhone 11 Pro Max,OS=13.1"
